name       : libfprint
version    : 0.99.0
release    : 2
source     :
    - https://gitlab.freedesktop.org/libfprint/libfprint/uploads/82ba3cef5bdf72997df711eacdb13c0f/libfprint-0.99.0.tar.xz : 0785974bc5d534492fde1e2e2a44a7cbaf8334f9ade2284f8959020f08b5249b
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library for fingerprint readers
description: |
    libfprint is an open source software library designed to make it easy for application developers to add support for consumer fingerprint readers to their software.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libusb-1.0)
    - pkgconfig(nss)
    - pkgconfig(pixman-1)
    - pkgconfig(xv)
setup      : |
    %meson_configure -D gtk-examples=false
build      : |
    %ninja_build
install    : |
    %ninja_install
