name       : libfprint
version    : 1.94.3
release    : 5
source     :
    - https://gitlab.freedesktop.org/libfprint/libfprint/-/archive/v1.94.3/libfprint-v1.94.3.tar.bz2 : bbd33aa6e92164289e85689e40162c3dfe8f11a8052f5cbd3021c00bfa1eb726
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library for fingerprint readers
description: |
    libfprint is an open source software library designed to make it easy for application developers to add support for consumer fingerprint readers to their software.
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(gusb)
    - pkgconfig(nss)
    - pkgconfig(pixman-1)
    - pkgconfig(xv)
setup      : |
    %meson_configure -Ddrivers=all
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
