name       : libfprint
version    : 1.90.1
release    : 4
source     :
    - https://gitlab.freedesktop.org/libfprint/libfprint/uploads/662cd834e76c02c4d74ad01c50412759/libfprint-1.90.1.tar.xz : bd03dd5e95db32d8cd3e5c91c582a0cdc634a14c20c419ac06b1445150d366df
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library for fingerprint readers
description: |
    libfprint is an open source software library designed to make it easy for application developers to add support for consumer fingerprint readers to their software.
builddeps  :
    - pkgconfig(gtk-doc)
    - pkgconfig(gusb)
    - pkgconfig(nss)
    - pkgconfig(pixman-1)
    - pkgconfig(xv)
setup      : |
    %meson_configure -Ddrivers=all
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
